# Generated by Django 5.1.4 on 2024-12-13 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1)),
                ('device_type', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100)),
                ('home_location_lat', models.FloatField()),
                ('home_location_long', models.FloatField()),
                ('home_country', models.CharField(max_length=100)),
                ('first_join_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('masterCategory', models.CharField(max_length=100)),
                ('subCategory', models.CharField(max_length=100)),
                ('articleType', models.CharField(max_length=100)),
                ('baseColour', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('usage', models.CharField(max_length=100)),
                ('productDisplayName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('booking_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(max_length=100)),
                ('product_metadata', models.JSONField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=10)),
                ('promo_amount', models.FloatField()),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_fee', models.FloatField()),
                ('shipment_date_limit', models.DateTimeField()),
                ('total_amount', models.FloatField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
